# Generated by Django 5.0.4 on 2024-07-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_massages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ('name',), 'permissions': [('deactivate_emailmessage', 'Can deactivate mailing'), ('view_all_emailmessage', 'Can view all mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
