# Generated by Django 5.0.4 on 2024-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('count_view', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
